_target_: src.models.flow_prediction_module.FlowPredictionModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.5
  patience: 4
  threshold: 0.1

net:
  _target_: src.models.components.dense_net.NeuralNetworkPlain
  layer_cnt: 10
  neuron_cnt: 1000
  activation_func: ReLU
  input_cnt: 9
  output_cnt: 1

# compile model for faster training with pytorch 2.0
compile: false
