defaults:
  - model_checkpoint
  - model_summary
  - rich_progress_bar

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/loss"
  patience: 100     # very patient
  mode: "max"

model_summary:
  max_depth: -1
